--- 
abstract: Find local cookies file(s) for current user
author: 
  - Martin Thurn <mthurn@cpan.org>
build_requires: 
  Test::More: 0
  Test::Simple: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTP-Cookies-Find
no_index: 
  directory: 
    - inc
    - t
recommends: 
  HTTP::Cookies::Microsoft: 0
  HTTP::Cookies::Mozilla: 0
  HTTP::Cookies::Netscape: 0
requires: 
  Config::IniFiles: 0
  File::HomeDir: 0
  File::Slurp: 0
  File::Spec: 0
  HTTP::Cookies: 0
  User: 0
  Win32::TieRegistry: 0
version: 1.413
